setwd('/Users/jaydiii/Desktop/JD_desktop/R_MiSeq/R_all')
library('ape')
library('phytools')
library('phyloseqCompanion')
library("ggplot2")
library("plyr")
library(factoextra)
#env.all <- read.table('NBP1910_envdataCTD_2021d.txt')
#envdata = sample_data(data.frame(cbind(data.frame(scale(env.all[c(5:22)])),env.all[c(1:4)])))
#envdata2 = sample_data(data.frame(scale(env.all[c(5:22)])))
#row.names(envdata2) <- env.all$sample
#env.pca <- prcomp(envdata2, center = TRUE, scale = TRUE)
#summary(env.pca)
#varexp <- env.pca$sdev^2/sum(env.pca$sdev^2)
#env.pca$x %>%
#as.data.frame %>%
#ggplot(aes(x=PC1,y=PC2)) + geom_point(size=4) + theme_bw(base_size=32) + labs(x=paste0("PC1: ", round(varexp[1]*100,1),"%"), y=paste0("PC2: ",round(varexp[2]*100,1), "%")) + theme(legend.position="top")


data.all <- read.table('OTUtable_ingroup_noTtree_part1.tsv')
mytable = otu_table(cbind(data.all[c(0)],data.all[c(16:111)]), taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('NBP1910_envdataCTD_2021.txt')
envdata = sample_data(env.all)
#tree <- phytools::read.newick('rename2.tree')
#phy_tree(tree, errorIfNULL=TRUE)
#test = read.table("VTaxo.txt", header=TRUE)
testb <- as.matrix(data.all[c(0:15)])
TAX <- tax_table(testb)
physeq <- phyloseq(mytable, envdata, tree, TAX)
pico <- subset_samples(physeq, size == "pico")
nano <- subset_samples(physeq, size == "nano")
micro <- subset_samples(physeq, size == "micro")
#PCoA <- ordinate(physeq, "PCoA", distance = "canberra")
dUNIFRAC = UniFrac(physeq, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA <- ordinate(physeq, "PCoA", distance = dUNIFRAC)
ordplotP <- plot_ordination(physeq, PCoA, color="Lat", shape="size",label="sample", title="Allsize")
ordplotPplus <- ordplotP + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.4, aes(fill=size))
quartz()
plot(ordplotPplus)

#PCoAm <- ordinate(micro, "PCoA", distance = "canberra")
dUNIFRACm = UniFrac(micro, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAm <- ordinate(micro, "PCoA", distance = dUNIFRACm)
ordplotPm <- plot_ordination(micro, PCoAm, color="Lat", shape="depth",label="sample",title="Micropk")
ordplotPmplus <- ordplotPm + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.4, aes(fill=depth))
quartz()
plot(ordplotPmplus)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACn = UniFrac(nano, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAn <- ordinate(nano, "PCoA", distance = dUNIFRACn)
ordplotPn <- plot_ordination(nano, PCoAn, color="Lat", shape="depth",label="sample",title="Nanopk")
quartz()
plot(ordplotPn)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACp = UniFrac(pico, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAp <- ordinate(pico, "PCoA", distance = dUNIFRACp)
ordplotPp <- plot_ordination(pico, PCoAp, color="Lat", shape="depth",label="sample",title="Picopk")
quartz()
plot(ordplotPp)

ordMDS <- metaMDS(t(otu_table(physeq)))
ordMDS.fit <- envfit(ordMDS ~ Lat + Long + bprod + pprod_Sun + pprod_PAR + ice + airT + depth_m + PAR1 + PAR2 + salinity1 + timeJ + latitude + longitude + oxygen1 + oxygenSaturation + fluorescence + beamTrans + waterT1 + conductivity1 + depSM + size_num, data=sample.data.table(physeq), perm=999, na.rm = TRUE)
plot(ordMDS, dis="site")
plot(ordMDS.fit)
text(ordMDS, display="sites")
ordMDS.fit
